// Friends
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'

// Diaries
export const GET_DIARIES_SUCCESS = 'GET_DIARIES_SUCCESS'
export const GET_DIARY_SUCCESS = 'GET_DIARY_SUCCESS'
export const CREATE_DIARY_SUCCESS = 'CREATE_DIARY_SUCCESS'
export const OPEN_DIARY_FORM = 'OPEN_DIARY_FORM'
export const CLOSE_DIARY_FORM = 'CLOSE_DIARY_FORM'
export const CLEAR_DIARY_FORM = 'CLEAR_DIARY_FORM'

export const FILL_DIARY_FORM = 'FILL_DIARY_FORM'
export const PARSE_DIARY_FORM_ERROR = 'PARSE_DIARY_FORM_ERROR'
export const CLEAR_DIARY_FORM_ERROR = 'CLEAR_DIARY_FORM_ERROR'
// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT'
