// Friends
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS'
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS'

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT'
